### ISSUE TITLE
Can't update User Metadata using the SDK.

### ISSUE THREAD

**Issue by noricane** [clerkinc/clerk-sdk-go#144]
Getting invalid memory address or nil pointer dereference when trying to update a user's metadata.

**code:**
```
//init client and whatnot
metadataJson,err := json.Marshal(metadata)
if err != nil {
	return err
}
clerkmetadata := &clerk.UpdateUserMetadata{
	PublicMetadata: metadataJson,
	PrivateMetadata: []byte{},
	UnsafeMetadata: []byte{},		
}
//Panics here on UpdateMetadata
user, err := client.Users().UpdateMetadata(clerkUser.ID,clerkmetadata)
if err != nil {
	fmt.Printf("ERROR UPDATING %v \n",err)
}else{
	fmt.Printf("UPDATED %v \n",user)
}
```

**Error:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7ed6f2]
goroutine 51 [running]:
github.com/clerkinc/clerk-sdk-go/clerk.(*client).Do(0xc000526000, 0x0, {0x9bf6c0, 0xc000202a00})
/root/go/pkg/mod/github.com/clerkinc/clerk-sdk-go@v1.45.0/clerk/clerk.go:216 +0xb2
github.com/clerkinc/clerk-sdk-go/clerk.(*UsersService).UpdateMetadata(0xc00069a080, {0xc000696fe0?, 0xaf2e5d?}, 0xc000216910)
/root/go/pkg/mod/github.com/clerkinc/clerk-sdk-go@v1.45.0/clerk/users.go:240 +0x163
mailapp-backend/database.UpdateUser({0xae57ae, 0x20})
/app/database/database_utils.go:71 +0x2ce
mailapp-backend/routes.UpdateUser(0xa17b20?)
/app/routes/user.go:68 +0x2a
github.com/gofiber/fiber/v2.(*App).next(0xc000272480, 0xc0002762c0)
/root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/router.go:144 +0x1bf
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000516330?)
/root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/ctx.go:913 +0x53
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc0002762c0)
/root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/middleware/cors/cors.go:162 +0x326
github.com/gofiber/fiber/v2.(*App).next(0xc000272480, 0xc0002762c0)
/root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/router.go:144 +0x1bf
github.com/gofiber/fiber/v2.(*App).handler(0xc000272480, 0x4c1ad7?)
/root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/router.go:171 +0x87
github.com/valyala/fasthttp.(*Server).serveConn(0xc0001aa800, {0xbc7638?, 0xc000012028})
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.48.0/server.go:2363 +0x11f5
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0006a6320, 0xc000866000)
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.48.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.48.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
/root/go/pkg/mod/github.com/valyala/fasthttp@v1.48.0/workerpool.go:195 +0x1b0
```

**Comment by georgepsarakis** [comment]
Hello @noricane ! Judging from the stacktrace, it seems that an error is returned during Client initialization thus resulting to a `nil` Client instance:

```go
client, err := clerk.NewClient(apiKey)
if err != nil {
    // handle error
}
```

Any chance that you haven't provided the API token for request authentication? Would you mind sharing the client initialization steps?

**Comment by noricane** [comment]
Hi  @georgepsarakis.
You're right, I fixed it now, it was from my side. 
Thanks for the help!

**Comment by georgepsarakis** [comment]
You're welcome @noricane , glad that we could help!

**Comment by noricane** [comment]
Looking at the SDK documentation I noticed some strange things on the update metadata example and I'm wondering if you have any insights as to why that is.

The first thing is that in the append it should be append(keyValStrings,....)
s.clerkClient should be client?
And then just a general question. Why do Users.Update instead of Users.UpdateMetadata?

I'm still relatively new to Golang so apologies if the comments are incorrect.

```
var client clerk.Client

func addStripeCustomerID(user *clerk.User, stripeCustomerID string) error {	
	currPrivMetadata := user.PrivateMetadata.(map[string]interface{})	
	currPrivMetadata["stripe_customer_id"] = stripeCustomerID

	var keyValStrings []string
	for key, value := range currPrivMetadata {
		keyValStrings = append(keysString, fmt.Sprintf("\"%s\": \"%s\"", key, value))
	}
	finalStr := fmt.Sprintf("{%s}", strings.Join(keysString, ","))
	user, err := s.clerkClient.Users().Update(sess.UserID, &clerk.UpdateUser{
		PrivateMetadata: finalStr,
	})

	if err != nil {
		panic(err)
	}
}
```

**Comment by georgepsarakis** [comment]
@noricane the `UpdateMetadata` endpoint behaves differently compared to `Update` as described in the [API reference documentation](https://clerk.com/docs/reference/backend-api/tag/Users#operation/UpdateUserMetadata).

> This endpoint behaves differently than the Update a user endpoint. Metadata values will not be replaced entirely. Instead, a deep merge will be performed. Deep means that any nested JSON objects will be merged as well.

Thus, it depends on the operation that you need to perform on the metadata attributes. If you need to replace the e.g. `PrivateMetadata` entirely, you can use `Update`. If you want to modify specific metadata values you should then use the `UpdateMetadata` method.

I hope this makes sense, let us know if you have more questions!
